apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 10m
  timeout: 30m
  chart:
    spec:
      chart: redis
      version: 21.2.14
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: redis
  values:
    architecture: replication
    auth:
      enabled: true
      existingSecret: ""
      existingSecretPasswordKey: ""
    master:
      persistence:
        enabled: true
        size: 8Gi
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
    replica:
      replicaCount: 2
      persistence:
        enabled: true
        size: 8Gi
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
    sentinel:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false