services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "9090"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: on-failure
    # Uncomment the following lines if you want to expose outside of the docker network.
    #ports:
    #  - 9090:9090
    #  - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_USERS: ${WEAVIATE_API_KEY_USER}
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_API_KEY}
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "node1"
