apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  timeout: 30m
  chart:
    spec:
      chart: flux2
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
  values:
    installCRDs: true
    policies:
      create: false
    sourceController:
      image:
        tag: v1.6.2
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
    kustomizeController:
      image:
        tag: v1.6.1
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
    helmController:
      image:
        tag: v1.3.0
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
    notificationController:
      image:
        tag: v1.6.0
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
    imageAutomationController:
      image:
        tag: v0.41.2
    imageReflectorController:
      image:
        tag: v0.35.2