apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  # This is a full dockerconfigjson:
  # {"auths":{"stackai.azurecr.io":{"username":"VALUE","password":"VALUE"}}}
  # cat acr.credentials.file | base64
  .dockerconfigjson: VALUE
