apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  # This is a full dockerconfigjson:
  # {"auths":{"stackai.azurecr.io":{"username":"curtis-k8s-development","password":"VALUE","email":"noreply@stackai.com","auth":"VALUE"}}}
  # cat acr.credentials.file | base64
  .dockerconfigjson: VALUE
