apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: flux-system
spec:
  values:
    # Azure-specific persistence configuration
    db:
      persistence:
        size: 32Gi
        storageClassName: supabase-premium-rwo
    
    storage:
      persistence:
        size: 20Gi
        storageClassName: supabase-premium-rwo
    
    imgproxy:
      persistence:
        size: 10Gi
        storageClassName: supabase-premium-rwo
    
    # Azure-optimized resource settings
    db:
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
    
    studio:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    auth:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    rest:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    realtime:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    meta:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    storage:
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
    
    imgproxy:
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
    
    # Kong configuration for Azure
    kong:
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
      
      # Azure internal load balancer configuration
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "default"
      
      # Remove AWS-specific ingress configuration
      ingress:
        enabled: false
    
    # Additional Azure-specific environment variables
    db:
      environment:
        # Azure-specific performance tuning
        POSTGRES_MAX_CONNECTIONS: "200"
        POSTGRES_SHARED_BUFFERS: "256MB"
        POSTGRES_EFFECTIVE_CACHE_SIZE: "1GB"
        POSTGRES_WORK_MEM: "4MB"
    
    # Functions configuration for Azure
    functions:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
