apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: supabase-secret-store
  namespace: supabase
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: supabase-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: supabase-sa
  namespace: supabase
  annotations:
    eks.amazonaws.com/role-arn: "${EXTERNAL_SECRETS_ROLE_ARN}"