apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  timeout: 30m
  chart:
    spec:
      chart: flux2
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
  values:
    installCRDs: true
    cli:
      image: ghcr.io/fluxcd/flux-cli
      tag: v2.3.0
    sourceController:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
    kustomizeController:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
    helmController:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
    notificationController:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi