apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-premium-rwo
parameters:
  skuName: Premium_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true